[bio]
name = "Josh Finnie"
avatar = "img/josh.jpg"
avatar_alt = "Josh Finnie's Avatar"
byline = "Senior engineer building things with code"
footer = "Â© 2026 - Josh Finnie"

[links]
[links.web]
url = "https://www.joshfinnie.com"
title = "joshfinnie.com"
[links.mailto]
url = "mailto:josh@jfin.us"
title = "josh@jfin.us"

[social]
[social.github]
url = "https://github.com/joshfinnie"
title = "joshfinnie"
[social.instagram]
url = "https://instagram.com/joshfinnie"
title = "joshfinnie"
[social.linkedin]
url = "https://linkedin.com/in/joshfinnie"
title = "joshfinnie"
[social.twitch]
url = "https://twitch.tv/joshfinnie"
title = "joshfinnie"
[social.youtube]
title = "@joshfinnie"
url = "https://youtube.com/@joshfinnie"
[social.threads]
title = "@joshfinnie"
url = "https://www.threads.net/@joshfinnie"
[social.bluesky]
url = "https://bsky.app/profile/joshfinnie.dev"
title = "@joshfinnie.dev"
